#!/bin/sh
crondir=${CRONDIR:-~/.cron}
if [ ! -d  "$crondir" ];then
    echo "$crondir doesn't exist yet. Set up your cron files first"
    exit 1
fi
cd $crondir
command=$1
if [ -n "$command" ];then
    shift
fi

help(){
    echo "Usage:"
    echo "crontroll status <cronjob>    get status of cronjob"
    echo "crontroll enable <cronjob>    enable cronjob"
    echo "crontroll disable <cronjob>   disable cronjob"
    echo "crontroll reload              reload cronjobs after adding or removing files in $crondir"
}

checkargs(){
    if [ -z "$1" ];then
        >&2 echo "Not enough arguments"
        help
        exit 1
    fi
}

reload_crontab(){
        (cat ~/.cron/* 2>/dev/null || echo "")|crontab -
}

comm1=`printf %.1s "$command"`
if [ "${comm1}" = "r" ];then
    reload_crontab
    exit
fi

checkargs $@
for f in "$@";do
    if [ ! -f "$f" ];then
        >&2 echo "$f not found"
        exit 1
    fi
    filecontent="`cat $f`"
    firstletter=`printf %.1s "$filecontent"`
    if [ "$firstletter" = '#' ];then
        cronjob="`echo \"${filecontent}\"|sed 's/^.//'`"
    else
        cronjob="${filecontent}"
    fi
    if [ "${comm1}" = "d" ]; then
        donesomething=true
        printf "#%s\n" "$cronjob" > $f
    elif [ "${comm1}" = "e" ];then
        donesomething=true
        printf "%s\n" "$cronjob" > $f
    elif [ "${comm1}" = "s" ];then
        donesomething=true
        if [ "$firstletter" = '#' ];then
            status="disabled"
        else
            status="enabled"
        fi
        printf "%s: %s; %s\n" "$status" "$f" "$cronjob"
    fi
done
if [ "$donesomething" = true ];then
    reload_crontab
else
    checkargs $command
    >&2 echo "Unknown command: $command"
fi
